[build]
  publish = "flippost-site"
  command = ""
  functions = "netlify/functions"

[[redirects]]
  from = "/landing"
  to = "/flipit-landing-page.html"
  status = 200

[[redirects]]
  from = "/thanks"
  to = "/thank-you.html"
  status = 200
